"""Integration tests for rh-skills formalize command."""

import json
import os
from pathlib import Path

import pytest
from click.testing import CliRunner
from ruamel.yaml import YAML

from rh_skills.commands.formalize import formalize, STRATEGY_REGISTRY
from tests.conftest import make_tracking, load_tracking


@pytest.fixture
def formalize_topic(tmp_repo):
    """Create a topic with an approved L2 artifact ready for formalization."""
    topic_dir = tmp_repo / "topics" / "test-topic"
    structured_dir = topic_dir / "structured"
    computable_dir = topic_dir / "computable"
    structured_dir.mkdir(parents=True)
    computable_dir.mkdir(parents=True)

    # Write L2 artifact
    y = YAML()
    y.default_flow_style = False
    l2 = {
        "artifact_schema_version": "1.0",
        "metadata": {"id": "test-rules", "title": "Test Decision Rules"},
        "decision_table": [{"condition": "temp > 38", "action": "order blood culture"}],
    }
    with open(structured_dir / "test-rules.yaml", "w") as f:
        y.dump(l2, f)

    # Write tracking with structured artifact
    make_tracking(tmp_repo, topics=[{
        "name": "test-topic",
        "structured": [{
            "name": "test-rules",
            "artifact_type": "decision-table",
            "status": "approved",
            "file": "topics/test-topic/structured/test-rules.yaml",
        }],
        "computable": [],
        "events": [],
    }])

    # Write formalize config
    process_dir = topic_dir / "process"
    process_dir.mkdir(parents=True, exist_ok=True)
    (process_dir / "formalize-config.yaml").write_text(
        "name: TestTopic\nid: test-topic\ncanonical: http://example.org/fhir\nstatus: draft\nversion: 0.1.0\n"
    )

    os.environ["LLM_PROVIDER"] = "stub"
    yield tmp_repo
    os.environ.pop("LLM_PROVIDER", None)


def _write_formalize_plan(
    topic_dir: Path,
    *,
    artifact_name: str,
    source_artifact: str = "test-rules",
    status: str = "approved",
    reviewer_decision: str = "approved",
):
    plans_dir = topic_dir / "process" / "plans"
    plans_dir.mkdir(parents=True, exist_ok=True)
    (plans_dir / "formalize-plan.yaml").write_text(
        "topic: test-topic\n"
        "plan_type: formalize\n"
        f"status: {status}\n"
        "artifacts:\n"
        f"  - name: {artifact_name}\n"
        f"    source_artifact: {source_artifact}\n"
        "    strategy: decision-table\n"
        "    implementation_target: true\n"
        f"    reviewer_decision: {reviewer_decision}\n"
    )


class TestFormalizeCommand:
    def test_dry_run(self, formalize_topic):
        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules", "--dry-run"])
        assert result.exit_code == 0
        assert "DRY RUN" in result.output
        assert "PlanDefinition" in result.output
        assert "eca-rule" in result.output

    def test_basic_formalize(self, formalize_topic):
        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code == 0, result.output
        assert "computable_converged" in result.output

        # Check files were written
        comp_dir = formalize_topic / "topics" / "test-topic" / "computable"
        json_files = list(comp_dir.glob("*.json"))
        assert len(json_files) >= 1

        # Check FHIR JSON structure
        for jf in json_files:
            resource = json.loads(jf.read_text())
            assert "resourceType" in resource
            assert "id" in resource

        # CQL is NOT auto-generated by formalize — the rh-inf-cql skill owns .cql files.
        # If a Library is in scope, formalize emits a guidance note instead.
        cql_files = list(comp_dir.glob("*.cql"))
        assert len(cql_files) == 0, (
            "formalize must NOT auto-generate .cql files — "
            "CQL authoring is delegated to `rh-inf-cql` (author mode)"
        )

    def test_decision_table_can_use_llm_provider(self, formalize_topic, monkeypatch):
        monkeypatch.setenv("LLM_PROVIDER", "openai")
        monkeypatch.setattr(
            "rh_skills.commands.formalize._invoke_llm",
            lambda _system, _user: json.dumps([
                {
                    "resourceType": "PlanDefinition",
                    "id": "llm-generated-rules",
                    "url": "http://example.org/fhir/PlanDefinition/llm-generated-rules",
                    "version": "0.1.0",
                    "status": "draft",
                    "date": "2026-06-01",
                    "name": "LlmGeneratedRules",
                    "title": "LLM Generated Rules PlanDefinition",
                }
            ]),
        )

        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules", "--force"])
        assert result.exit_code == 0, result.output
        assert "Using deterministic CPG-on-FHIR builders" not in result.output
        assert (formalize_topic / "topics" / "test-topic" / "computable" / "PlanDefinition-llm-generated-rules.json").exists()

    def test_tracking_updated(self, formalize_topic):
        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code == 0

        tracking = load_tracking(formalize_topic)
        topic = next(t for t in tracking["topics"] if t["name"] == "test-topic")

        # Check computable entry
        assert len(topic["computable"]) == 1
        entry = topic["computable"][0]
        assert entry["name"] == "test-rules"
        assert isinstance(entry["files"], list)
        assert isinstance(entry["checksums"], dict)
        assert entry["converged_from"] == ["test-rules"]
        assert entry["strategy"] == "decision-table"

        # Check event
        events = topic["events"]
        assert any(e["type"] == "computable_converged" for e in events)

    def test_artifact_not_found(self, formalize_topic):
        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "nonexistent"])
        assert result.exit_code != 0
        assert "not found" in result.output

    def test_topic_not_found(self, formalize_topic):
        runner = CliRunner()
        result = runner.invoke(formalize, ["nonexistent-topic", "test-rules"])
        assert result.exit_code != 0

    def test_force_overwrite(self, formalize_topic):
        runner = CliRunner()
        # First run
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code == 0

        # Second run without force — should fail on existing files
        result2 = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result2.exit_code != 0 or "already exists" in (result2.output + (result2.stderr or ""))

        # Third run with force — should succeed
        result3 = runner.invoke(formalize, ["test-topic", "test-rules", "--force"])
        assert result3.exit_code == 0

        tracking = load_tracking(formalize_topic)
        topic = next(t for t in tracking["topics"] if t["name"] == "test-topic")
        assert len(topic["computable"]) == 1

    def test_non_target_artifact_is_not_blocked_by_approved_formalize_plan_target(self, formalize_topic):
        topic_dir = formalize_topic / "topics" / "test-topic"
        _write_formalize_plan(topic_dir, artifact_name="different-artifact", source_artifact="different-artifact")

        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code == 0, result.output
        assert "not the approved implementation target" in result.output.lower()

    def test_matches_approved_target_by_source_artifact(self, formalize_topic):
        topic_dir = formalize_topic / "topics" / "test-topic"
        _write_formalize_plan(topic_dir, artifact_name="synthetic-target-name")

        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code == 0, result.output

    def test_rejects_unapproved_formalize_plan(self, formalize_topic):
        topic_dir = formalize_topic / "topics" / "test-topic"
        _write_formalize_plan(topic_dir, artifact_name="test-rules", status="pending-review")

        runner = CliRunner()
        result = runner.invoke(formalize, ["test-topic", "test-rules"])
        assert result.exit_code != 0
        assert "not approved" in result.output.lower()

class TestUnknownTypeFallback:
    def test_unknown_type_falls_back(self, tmp_repo):
        """FR-009: Unknown artifact_type falls back to generic strategy."""
        topic_dir = tmp_repo / "topics" / "test-topic"
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        # Write L2 with unknown type
        y = YAML()
        y.default_flow_style = False
        with open(structured_dir / "custom-artifact.yaml", "w") as f:
            y.dump({"metadata": {"id": "custom"}}, f)

        make_tracking(tmp_repo, topics=[{
            "name": "test-topic",
            "structured": [{
                "name": "custom-artifact",
                "artifact_type": "custom-unknown-type",
                "status": "approved",
            }],
            "computable": [],
            "events": [],
        }])

        # Write formalize config
        process_dir = topic_dir / "process"
        process_dir.mkdir(parents=True, exist_ok=True)
        (process_dir / "formalize-config.yaml").write_text(
            "name: TestTopic\nid: test-topic\ncanonical: http://example.org/fhir\nstatus: draft\nversion: 0.1.0\n"
        )

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, ["test-topic", "custom-artifact"])
            assert result.exit_code == 0, result.output

            # Check tracking records generic strategy
            tracking = load_tracking(tmp_repo)
            topic = next(t for t in tracking["topics"] if t["name"] == "test-topic")
            entry = topic["computable"][0]
            assert entry["strategy"] == "generic"
        finally:
            os.environ.pop("LLM_PROVIDER", None)


class TestStrategyRegistry:
    def test_all_supported_types_registered(self):
        expected = {
            "evidence-summary", "decision-table", "care-pathway",
            "terminology", "measure", "assessment", "policy",
            "eligibility-criteria", "risk-factors", "custom",
        }
        assert set(STRATEGY_REGISTRY.keys()) == expected

    def test_each_strategy_has_required_keys(self):
        for atype, strategy in STRATEGY_REGISTRY.items():
            assert "primary" in strategy, f"{atype} missing primary"
            assert "supporting" in strategy, f"{atype} missing supporting"
            assert "description" in strategy, f"{atype} missing description"


class TestCqlEmbedding:
    """CQL source is embedded as base64 content in Library JSON when present."""

    def _make_measure_topic(self, tmp_repo):
        topic_dir = tmp_repo / "topics" / "test-measure"
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        y = YAML()
        y.default_flow_style = False
        with open(structured_dir / "test-measure.yaml", "w") as f:
            y.dump({
                "metadata": {"id": "test-measure", "title": "Test Measure"},
                "populations": [{"id": "ip", "type": "initial-population"}],
            }, f)

        make_tracking(tmp_repo, topics=[{
            "name": "test-measure",
            "structured": [{
                "name": "test-measure",
                "artifact_type": "measure",
                "status": "approved",
                "file": "topics/test-measure/structured/test-measure.yaml",
            }],
            "computable": [],
            "events": [],
        }])

        # Write formalize config
        process_dir = topic_dir / "process"
        process_dir.mkdir(parents=True, exist_ok=True)
        (process_dir / "formalize-config.yaml").write_text(
            "name: TestMeasure\nid: test-measure\ncanonical: http://example.org/fhir\nstatus: draft\nversion: 0.1.0\n"
        )

        return computable_dir

    def test_cql_embedded_when_file_present(self, tmp_repo):
        """Library JSON gets content[].data (base64 CQL) when .cql exists in computable/."""
        import base64

        computable_dir = self._make_measure_topic(tmp_repo)
        cql_source = b"library TestMeasureLogic version '1.0.0'\nusing FHIR version '4.0.1'\n"
        (computable_dir / "TestMeasureLogic.cql").write_bytes(cql_source)

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, ["test-measure", "test-measure"])
            assert result.exit_code == 0, result.output
            assert "Embedded CQL source" in result.output

            lib_files = list(computable_dir.glob("Library-*.json"))
            assert len(lib_files) == 1, "Expected exactly one Library JSON"
            library = json.loads(lib_files[0].read_text())
            content = library.get("content", [])
            cql_items = [c for c in content if c.get("contentType") == "text/cql"]
            assert len(cql_items) == 1, "Expected one text/cql content item"
            decoded = base64.b64decode(cql_items[0]["data"])
            assert decoded == cql_source
        finally:
            os.environ.pop("LLM_PROVIDER", None)


class TestDeterministicFormalizeRegression:
    def _make_measure_topic(self, tmp_repo):
        topic_dir = tmp_repo / "topics" / "test-measure"
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        y = YAML()
        y.default_flow_style = False
        with open(structured_dir / "test-measure.yaml", "w") as f:
            y.dump({
                "metadata": {"id": "test-measure", "title": "Test Measure"},
                "populations": [{"id": "ip", "type": "initial-population"}],
            }, f)

        make_tracking(tmp_repo, topics=[{
            "name": "test-measure",
            "structured": [{
                "name": "test-measure",
                "artifact_type": "measure",
                "status": "approved",
                "file": "topics/test-measure/structured/test-measure.yaml",
            }],
            "computable": [],
            "events": [],
        }])

        process_dir = topic_dir / "process"
        process_dir.mkdir(parents=True, exist_ok=True)
        (process_dir / "formalize-config.yaml").write_text(
            "name: TestMeasure\nid: test-measure\ncanonical: http://example.org/fhir\nstatus: draft\nversion: 0.1.0\n"
        )

        return computable_dir

    def _write_topic_config(self, topic_dir: Path, topic: str):
        process_dir = topic_dir / "process"
        process_dir.mkdir(parents=True, exist_ok=True)
        (process_dir / "formalize-config.yaml").write_text(
            f"name: {''.join(w.capitalize() for w in topic.split('-'))}\n"
            f"id: {topic}\n"
            "canonical: http://example.org/fhir\n"
            "status: active\n"
            "version: 2.1.0\n"
        )

    def test_stub_mode_builds_structured_decision_table_scaffolds(self, tmp_repo):
        topic = "det-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
version: 9.9.9
sections:
  events:
    - id: intake
      label: Intake started
    - id: review
      label: Review started
  conditions:
    - id: severe
      label: Severe symptoms
      values: [true, false]
  actions:
    - id: order-ct
      label: Order sinus CT
      type: diagnostic-test
      do_not_perform: true
    - id: counsel
      label: Counsel patient
      type: communication
      intent: proposal
  rules:
    - id: r1
      event: intake
      when: {severe: true}
      then: [order-ct]
    - id: r2
      event: review
      when: {severe: false}
      then: [counsel]
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [{"name": "dt", "artifact_type": "decision-table", "status": "approved"}],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "dt"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output

            computable = topic_dir / "computable"
            assert (computable / "PlanDefinition-dt.json").exists()
            assert (computable / "PlanDefinition-dt-intake.json").exists()
            assert (computable / "PlanDefinition-dt-review.json").exists()
            assert (computable / "Library-dt-logic.json").exists()
            activity = json.loads((computable / "ActivityDefinition-order-ct.json").read_text())
            assert activity["kind"] == "ServiceRequest"
            assert activity["doNotPerform"] is True
            assert activity["status"] == "active"
            assert activity["version"] == "2.1.0"
            assert "code" not in activity
            plan = json.loads((computable / "PlanDefinition-dt.json").read_text())
            child_plan = json.loads((computable / "PlanDefinition-dt-intake.json").read_text())
            assert len(plan["action"]) == 2
            assert plan["library"][0].endswith("/Library/dt-logic")
            assert plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-intake")
            assert child_plan["library"][0].endswith("/Library/dt-logic")
            assert plan["meta"]["profile"] == ["http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-recommendationdefinition"]
            assert child_plan["meta"]["profile"] == ["http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-recommendationdefinition"]
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_decision_table_assessment_action_links_questionnaire(self, tmp_repo):
        topic = "assessment-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: intake
      label: Intake
      trigger_type: named-event
  conditions:
    - id: burden
      label: Quality of life burden documented
      values: [Yes, No]
  data_elements:
    - id: snot-22
      condition_id: burden
      label: SNOT-22 score
      data_type: patient-reported
  actions:
    - id: assess-surgical-candidacy
      label: Assess surgical candidacy
      kind: ServiceRequest
    - id: complete-qol-assessment
      label: Complete quality of life assessment
      kind: assessment
      parent_action_id: assess-surgical-candidacy
      assessment_artifact: qol-assessment
      produces_conditions: [burden]
  rules:
    - id: r1
      event: intake
      then: [assess-surgical-candidacy, complete-qol-assessment]
"""
        )
        (structured_dir / "qol-assessment.yaml").write_text(
            """\
artifact_type: assessment
title: Sinonasal Outcome Test 22
description: Questionnaire for sinonasal symptom burden.
sections:
  items:
    - id: q1
      text: How severe is nasal obstruction?
      type: ordinal
      options:
        - label: None
          value: 0
        - label: Severe
          value: 5
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "qol-assessment", "artifact_type": "assessment", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "dt"])
            assert result.exit_code == 0, result.output

            computable = topic_dir / "computable"
            activity = json.loads((computable / "ActivityDefinition-complete-qol-assessment.json").read_text())
            child_plan = json.loads((computable / "PlanDefinition-dt-intake.json").read_text())
            assert activity["kind"] == "Task"
            assert activity["meta"]["profile"][0] == "http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-collectinformationactivity"
            assert activity["profile"] == "http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-questionnairetask"
            assert activity["code"]["coding"][0]["system"] == "http://hl7.org/fhir/uv/cpg/CodeSystem/cpg-activity-type-cs"
            assert activity["code"]["coding"][0]["code"] == "collect-information"
            assert activity["extension"][0]["url"] == "http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-collectWith"
            assert activity["extension"][0]["valueCanonical"].endswith("/Questionnaire/qol-assessment")
            dynamic_values = {dv["path"]: dv["expression"] for dv in activity.get("dynamicValue", [])}
            assert dynamic_values["input.type"]["language"] == "text/cql"
            assert dynamic_values["input.type"]["expression"] == "code"
            assert dynamic_values["input.value"]["language"] == "text/cql"
            assert dynamic_values["input.value"]["expression"] == "extension('http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-collectWith').value"
            assert activity["relatedArtifact"][0]["resource"].endswith("/Questionnaire/qol-assessment")
            assert not (computable / "Questionnaire-qol-assessment.json").exists()
            assert child_plan["action"][0]["action"][0]["id"] == "assess-surgical-candidacy"
            assert child_plan["action"][0]["action"][0]["action"][0]["id"] == "complete-qol-assessment"

            assessment_result = runner.invoke(formalize, [topic, "qol-assessment"])
            assert assessment_result.exit_code == 0, assessment_result.output
            questionnaire = json.loads((computable / "Questionnaire-qol-assessment.json").read_text())
            assert questionnaire["resourceType"] == "Questionnaire"
            assert questionnaire["item"][0]["linkId"] == "q1"
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_builds_flat_care_pathway_scaffold_from_steps(self, tmp_repo):
        topic = "link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: intake
      label: Intake started
      trigger_type: named-event
    - id: assessment
      label: Assessment complete
      trigger_type: named-event
  conditions:
    - id: severe
      label: Severe symptoms
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: order
  rules:
    - id: r1
      event: intake
      phase: planning
      when: {severe: Yes}
      then: [order-ct]
    - id: r2
      event: assessment
      phase: execution
      when: {severe: true}
      then: [order-ct]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: planning
      label: Planning
      description: Initial planning phase
    - id: execution
      label: Execution
      description: Execution phase
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            pathway = json.loads((topic_dir / "computable" / "PlanDefinition-path.json").read_text())
            assert (topic_dir / "computable" / "PlanDefinition-path-planning.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-execution.json").exists()

            planning = pathway["action"][0]
            assert planning["id"] == "planning"
            assert planning["definitionCanonical"].endswith("/PlanDefinition/dt-intake")
            execution = pathway["action"][1]
            assert execution["id"] == "execution"
            assert execution["definitionCanonical"].endswith("/PlanDefinition/dt-assessment")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_keeps_unlinked_care_pathway_nodes_as_scaffold_actions(self, tmp_repo):
        topic = "optional-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: intake
      label: Intake started
    - id: assessment
      label: Assessment complete
    - id: planning
      label: Planning event
  conditions:
    - id: severe
      label: Severe symptoms
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: order
  rules:
    - id: r1
      event: intake
      phase: phase1
      when: {severe: Yes}
      then: [order-ct]
    - id: r2
      event: assessment
      when: {severe: Yes}
      then: [order-ct]
    - id: r3
      event: planning
      phase: phase2
      when: {severe: true}
      then: [order-ct]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: phase1
      label: Phase 1
      description: First phase (has rule.phase linking)
    - id: phase2
      label: Phase 2
      description: Second phase (has rule.phase linking)
    - id: phase3
      label: Phase 3
      description: Third phase (no rule.phase linking)
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            pathway = json.loads((topic_dir / "computable" / "PlanDefinition-path.json").read_text())
            assert [action["id"] for action in pathway["action"]] == ["phase1", "phase2", "phase3"]
            assert pathway["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-intake")
            assert pathway["action"][1]["definitionCanonical"].endswith("/PlanDefinition/dt-planning")
            assert "definitionCanonical" not in pathway["action"][2]
            assert (topic_dir / "computable" / "PlanDefinition-path-phase1.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-phase2.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-phase3.json").exists()
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_builds_hierarchical_care_pathway_scaffold_from_parent_id(self, tmp_repo):
        topic = "hierarchical-pathway-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: verify-diagnosis
      label: Verify diagnosis
      phase: assessment
    - id: assess-candidacy
      label: Assess candidacy
      phase: planning
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: ServiceRequest
  rules:
    - id: r1
      event: verify-diagnosis
      phase: assessment
      when: {confirmed: Yes}
      then: [order-ct]
    - id: r2
      event: assess-candidacy
      phase: planning
      when: {confirmed: Yes}
      then: [order-ct]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS surgical pathway
    - id: assessment
      label: Assessment
      description: Verify diagnosis and baseline status
      parent_id: crs-pathway
    - id: planning
      label: Planning
      description: Assess candidacy and plan next steps
      parent_id: crs-pathway
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            assert "enabling strategy PlanDefinition generation" not in result.output

            pathway = json.loads((topic_dir / "computable" / "PlanDefinition-path.json").read_text())
            assert [a["id"] for a in pathway["action"]] == ["crs-pathway"]
            assert [a["id"] for a in pathway["action"][0]["action"]] == ["assessment", "planning"]
            assert pathway["action"][0]["action"][0]["definitionCanonical"].endswith("/PlanDefinition/path-assessment")
            assert pathway["action"][0]["action"][1]["definitionCanonical"].endswith("/PlanDefinition/path-planning")
            assert (topic_dir / "computable" / "PlanDefinition-path-assessment.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-planning.json").exists()
            assessment_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-assessment.json").read_text())
            planning_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-planning.json").read_text())
            assert assessment_plan["type"]["coding"][0]["code"] == "workflow-definition"
            assert planning_plan["type"]["coding"][0]["code"] == "workflow-definition"
            assert assessment_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-verify-diagnosis")
            assert planning_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-assess-candidacy")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_hierarchical_root_does_not_require_phase_alignment(self, tmp_repo):
        topic = "hierarchical-root-alignment-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  pathway_phases:
    - id: assessment
      label: Assessment
    - id: planning
      label: Planning
  events:
    - id: verify-diagnosis
      label: Verify diagnosis
      phase: assessment
    - id: assess-candidacy
      label: Assess candidacy
      phase: planning
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: ServiceRequest
  rules:
    - id: r1
      event: verify-diagnosis
      phase: assessment
      when: {confirmed: Yes}
      then: [order-ct]
    - id: r2
      event: assess-candidacy
      phase: planning
      when: {confirmed: Yes}
      then: [order-ct]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS surgical pathway
    - id: assessment
      label: Assessment
      description: Verify diagnosis and baseline status
      parent_id: crs-pathway
    - id: planning
      label: Planning
      description: Assess candidacy and plan next steps
      parent_id: crs-pathway
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            assert "Phase 'crs-pathway' defined in care-pathway but not in decision-table phases" not in result.output
            assert "Phase 'crs-pathway' has no mapped events" not in result.output
            pathway = json.loads((topic_dir / "computable" / "PlanDefinition-path.json").read_text())
            assert [a["id"] for a in pathway["action"]] == ["crs-pathway"]
            assert pathway["action"][0]["action"][0]["definitionCanonical"].endswith("/PlanDefinition/path-assessment")
            assert pathway["action"][0]["action"][1]["definitionCanonical"].endswith("/PlanDefinition/path-planning")
            assert (topic_dir / "computable" / "PlanDefinition-path-assessment.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-planning.json").exists()
            assessment_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-assessment.json").read_text())
            planning_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-planning.json").read_text())
            assert assessment_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-verify-diagnosis")
            assert planning_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-assess-candidacy")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_care_pathway_step_rule_id_drives_recommendation_link(self, tmp_repo):
        topic = "pathway-rule-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: verify-diagnosis
      label: Verify diagnosis
      phase: assessment
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: verify-crs-diagnosis
      label: Verify CRS diagnosis
      kind: ServiceRequest
  rules:
    - id: rule-verify-diagnosis
      event: verify-diagnosis
      phase: assessment
      when: {confirmed: Yes}
      then: [verify-crs-diagnosis]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS surgical pathway
    - id: assessment-branch
      label: Assessment and surgical decision
      description: Assessment branch
      parent_id: crs-pathway
    - id: diagnosis-check
      label: Diagnostic verification checkpoint
      description: Confirm CRS diagnosis before further recommendations
      parent_id: assessment-branch
      rule_id: rule-verify-diagnosis
      action_labels:
        - Verify CRS diagnosis
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output

            assessment_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-assessment-branch.json").read_text())
            leaf_action = assessment_plan["action"][0]["action"][0]
            assert leaf_action["id"] == "diagnosis-check"
            assert leaf_action["definitionCanonical"].endswith("/ActivityDefinition/verify-crs-diagnosis")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_generic_artifact_names_expand_to_semantic_computable_ids(self, tmp_repo):
        topic = "generic-naming-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "decision-table.yaml").write_text(
            """\
id: decision-table
name: decision-table
title: Chronic Rhinosinusitis Surgical Management Decision Table
artifact_type: decision-table
sections:
  events:
    - id: verify-diagnosis
      label: Verify diagnosis
      phase: assessment
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: ServiceRequest
  rules:
    - id: r1
      event: verify-diagnosis
      phase: assessment
      when: {confirmed: Yes}
      then: [order-ct]
"""
        )
        (structured_dir / "care-pathway.yaml").write_text(
            """\
id: care-pathway
name: care-pathway
title: Chronic Rhinosinusitis Surgical Management Care Pathway
artifact_type: care-pathway
metadata:
  derived_from: [decision-table]
sections:
  steps:
    - id: crs-journey
      label: CRS journey
      description: Overall CRS journey
    - id: assessment
      label: Assessment
      description: Verify diagnosis
      parent_id: crs-journey
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "decision-table", "artifact_type": "decision-table", "status": "approved"},
                {"name": "care-pathway", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            dt_result = runner.invoke(formalize, [topic, "decision-table"])
            assert dt_result.exit_code == 0, dt_result.output
            assert "Using deterministic CPG-on-FHIR builders" not in dt_result.output
            cp_result = runner.invoke(formalize, [topic, "care-pathway"])
            assert cp_result.exit_code == 0, cp_result.output
            assert "Using deterministic CPG-on-FHIR builders" not in cp_result.output

            computable = topic_dir / "computable"
            assert (computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-recommendation.json").exists()
            assert (computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-recommendation-verify-diagnosis.json").exists()
            assert (computable / "Library-chronic-rhinosinusitis-surgical-management-recommendation-logic.json").exists()
            assert (computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-protocol.json").exists()
            assert (computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-protocol-assessment.json").exists()
            assert not (computable / "ActivityDefinition-chronic-rhinosinusitis-surgical-management-protocol-activity.json").exists()
            protocol = json.loads((computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-protocol.json").read_text())
            recommendation = json.loads((computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-recommendation-verify-diagnosis.json").read_text())
            strategy = json.loads((computable / "PlanDefinition-chronic-rhinosinusitis-surgical-management-protocol-assessment.json").read_text())
            assert protocol["type"]["coding"][0]["system"] == "http://terminology.hl7.org/CodeSystem/plan-definition-type"
            assert protocol["type"]["coding"][0]["display"] == "Clinical Protocol"
            assert recommendation["type"]["coding"][0]["system"] == "http://terminology.hl7.org/CodeSystem/plan-definition-type"
            assert recommendation["type"]["coding"][0]["display"] == "ECA Rule"
            assert protocol["meta"]["profile"] == ["http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-pathwaydefinition"]
            assert strategy["meta"]["profile"] == ["http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-strategydefinition"]
            assert recommendation["meta"]["profile"] == ["http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-recommendationdefinition"]
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_hierarchical_care_pathway_keeps_root_and_children_without_strategy_files(self, tmp_repo):
        topic = "hierarchical-fallback-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: verify-diagnosis
      label: Verify diagnosis
    - id: assess-candidacy
      label: Assess candidacy
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: order-ct
      label: Order sinus CT
      kind: ServiceRequest
  rules:
    - id: r1
      event: verify-diagnosis
      when: {confirmed: Yes}
      then: [order-ct]
    - id: r2
      event: assess-candidacy
      when: {confirmed: Yes}
      then: [order-ct]
"""
        )
        (structured_dir / "path.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [dt]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS surgical pathway
    - id: assessment
      label: Assessment
      description: Verify diagnosis and baseline status
      parent_id: crs-pathway
    - id: planning
      label: Planning
      description: Assess candidacy and plan next steps
      parent_id: crs-pathway
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "dt", "artifact_type": "decision-table", "status": "approved"},
                {"name": "path", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "path"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output

            pathway = json.loads((topic_dir / "computable" / "PlanDefinition-path.json").read_text())
            assert [a["id"] for a in pathway["action"]] == ["crs-pathway"]
            assert [a["id"] for a in pathway["action"][0]["action"]] == ["assessment", "planning"]
            assert pathway["action"][0]["action"][0]["definitionCanonical"].endswith("/PlanDefinition/path-assessment")
            assert pathway["action"][0]["action"][1]["definitionCanonical"].endswith("/PlanDefinition/path-planning")
            assert (topic_dir / "computable" / "PlanDefinition-path-assessment.json").exists()
            assert (topic_dir / "computable" / "PlanDefinition-path-planning.json").exists()
            assessment_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-assessment.json").read_text())
            planning_plan = json.loads((topic_dir / "computable" / "PlanDefinition-path-planning.json").read_text())
            assert assessment_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-verify-diagnosis")
            assert planning_plan["action"][0]["definitionCanonical"].endswith("/PlanDefinition/dt-assess-candidacy")
            assert not (topic_dir / "computable" / "PlanDefinition-path-crs-pathway.json").exists()
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_care_pathway_semantically_links_steps_to_recommendation_plans(self, tmp_repo):
        topic = "semantic-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "decision-table.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: event-assess-candidacy
      label: Adult with verified CRS asks about surgery
      phase: candidacy-assessment
    - id: event-operative-planning
      label: Surgeon determines operative extent for scheduled CRS surgery
      phase: perioperative-management
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: assess-surgical-candidacy
      label: Assess surgical candidacy
      kind: ServiceRequest
    - id: perform-full-exposure-surgery
      label: Perform full exposure surgery
      kind: Procedure
  rules:
    - id: r1
      event: event-assess-candidacy
      phase: candidacy-assessment
      when: {confirmed: Yes}
      then: [assess-surgical-candidacy]
    - id: r2
      event: event-operative-planning
      phase: perioperative-management
      when: {confirmed: Yes}
      then: [perform-full-exposure-surgery]
"""
        )
        (structured_dir / "care-pathway.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [decision-table]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS pathway
    - id: assess-candidacy
      label: Assess candidacy for sinus surgery
      description: Review burden and prior therapy before surgery.
      parent_id: crs-pathway
    - id: perform-definitive-surgery
      label: Perform appropriately extensive surgery
      description: Choose full exposure rather than limited dilation when advanced findings are present.
      parent_id: crs-pathway
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "decision-table", "artifact_type": "decision-table", "status": "approved"},
                {"name": "care-pathway", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            assert runner.invoke(formalize, [topic, "decision-table"]).exit_code == 0
            result = runner.invoke(formalize, [topic, "care-pathway"])
            assert result.exit_code == 0, result.output

            computable = topic_dir / "computable"
            protocol_path = next(computable.glob("PlanDefinition-*-protocol.json"))
            pathway = json.loads(protocol_path.read_text())
            child_nodes = pathway["action"][0]["action"]
            assert child_nodes[0]["definitionCanonical"].endswith("/PlanDefinition/semantic-link-topic-protocol-assess-candidacy")
            assert child_nodes[1]["definitionCanonical"].endswith("/PlanDefinition/semantic-link-topic-protocol-perform-definitive-surgery")

            assess_plan = json.loads((computable / "PlanDefinition-semantic-link-topic-protocol-assess-candidacy.json").read_text())
            assert assess_plan["type"]["coding"][0]["code"] == "workflow-definition"
            nested = assess_plan["action"][0]["definitionCanonical"]
            assert nested.endswith("/PlanDefinition/semantic-link-topic-recommendation-event-assess-candidacy")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_care_pathway_does_not_reuse_one_recommendation_for_multiple_steps(self, tmp_repo):
        topic = "duplicate-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "decision-table.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: event-operative-planning
      label: Surgeon determines operative extent for scheduled CRS surgery
      phase: perioperative-management
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: perform-full-exposure-surgery
      label: Perform full exposure surgery
      kind: Procedure
  rules:
    - id: r1
      event: event-operative-planning
      phase: perioperative-management
      when: {confirmed: Yes}
      then: [perform-full-exposure-surgery]
"""
        )
        (structured_dir / "care-pathway.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [decision-table]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall CRS pathway
    - id: offer-and-plan-surgery
      label: Offer and plan sinus surgery
      description: Offer surgery when expected benefits exceed nonsurgical management.
      parent_id: crs-pathway
    - id: perform-definitive-surgery
      label: Perform appropriately extensive surgery
      description: Choose full exposure rather than limited dilation when advanced findings are present.
      parent_id: crs-pathway
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "decision-table", "artifact_type": "decision-table", "status": "approved"},
                {"name": "care-pathway", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            assert runner.invoke(formalize, [topic, "decision-table"]).exit_code == 0
            result = runner.invoke(formalize, [topic, "care-pathway"])
            assert result.exit_code == 0, result.output

            computable = topic_dir / "computable"
            protocol_path = next(computable.glob("PlanDefinition-*-protocol.json"))
            pathway = json.loads(protocol_path.read_text())
            child_nodes = pathway["action"][0]["action"]
            linked = [node["definitionCanonical"] for node in child_nodes]
            assert linked[0].endswith("/PlanDefinition/duplicate-link-topic-protocol-offer-and-plan-surgery")
            assert linked[1].endswith("/PlanDefinition/duplicate-link-topic-protocol-perform-definitive-surgery")

            surgery_plan = json.loads((computable / "PlanDefinition-duplicate-link-topic-protocol-perform-definitive-surgery.json").read_text())
            assert "definitionCanonical" not in surgery_plan["action"][0]
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_stub_mode_care_pathway_leaf_step_can_link_directly_to_decision_table_activity(self, tmp_repo):
        topic = "leaf-action-link-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()

        (structured_dir / "decision-table.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events:
    - id: event-assess-candidacy
      label: Assess candidacy
  conditions:
    - id: confirmed
      label: Confirmed
      values: [Yes, No]
  actions:
    - id: assess-surgical-candidacy
      label: Assess surgical candidacy
      kind: ServiceRequest
    - id: administer-snot-22-assessment
      label: Administer or review SNOT-22 assessment
      kind: Task
  rules:
    - id: r1
      event: event-assess-candidacy
      when: {confirmed: Yes}
      then: [assess-surgical-candidacy, administer-snot-22-assessment]
"""
        )
        (structured_dir / "care-pathway.yaml").write_text(
            """\
artifact_type: care-pathway
metadata:
  derived_from: [decision-table]
sections:
  steps:
    - id: crs-pathway
      label: CRS pathway
      description: Overall pathway
    - id: assess-candidacy
      label: Assess candidacy
      description: Overall candidacy assessment
      parent_id: crs-pathway
    - id: qol-questionnaire
      label: Administer or review validated CRS quality-of-life questionnaire
      description: Use a validated instrument such as SNOT-22 when it contributes meaningfully to candidacy assessment.
      parent_id: assess-candidacy
      rule_id: r1
      action_labels:
        - Administer or review SNOT-22 assessment
"""
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [
                {"name": "decision-table", "artifact_type": "decision-table", "status": "approved"},
                {"name": "care-pathway", "artifact_type": "care-pathway", "status": "approved"},
            ],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            assert runner.invoke(formalize, [topic, "decision-table"]).exit_code == 0
            result = runner.invoke(formalize, [topic, "care-pathway"])
            assert result.exit_code == 0, result.output

            branch_plan = json.loads((topic_dir / "computable" / "PlanDefinition-leaf-action-link-topic-protocol-assess-candidacy.json").read_text())
            questionnaire_step = branch_plan["action"][0]["action"][0]
            assert questionnaire_step["definitionCanonical"].endswith("/ActivityDefinition/administer-snot-22-assessment")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_formalize_prefers_packager_toml_canonical(self, tmp_repo):
        topic = "canonical-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()
        (structured_dir / "dt.yaml").write_text(
            """\
artifact_type: decision-table
sections:
  events: [{id: intake, label: Intake, trigger_type: named-event}]
  conditions: [{id: severe, label: Severe, values: [Yes, No]}]
  actions: [{id: order-ct, label: Order CT, kind: order}]
  rules: [{id: r1, event: intake, when: {severe: Yes}, then: [order-ct]}]
"""
        )
        self._write_topic_config(topic_dir, topic)
        workspace = topic_dir / "process" / "package-workspace"
        workspace.mkdir(parents=True, exist_ok=True)
        (workspace / "packager.toml").write_text(
            'id = "reason.canonical-topic"\nversion = "1.0.0"\ncanonical = "https://packager.example/fhir"\nstatus = "active"\n'
        )
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [{"name": "dt", "artifact_type": "decision-table", "status": "approved"}],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "dt"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            pd = json.loads((topic_dir / "computable" / "PlanDefinition-dt.json").read_text())
            assert pd["url"].startswith("https://packager.example/fhir/")
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_non_pathway_artifacts_keep_non_deterministic_stub_path(self, tmp_repo):
        topic = "measure-topic"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        structured_dir.mkdir(parents=True)
        (topic_dir / "computable").mkdir()
        (structured_dir / "measure.yaml").write_text(
            "artifact_type: measure\nsections: {}\n"
        )
        self._write_topic_config(topic_dir, topic)
        make_tracking(tmp_repo, topics=[{
            "name": topic,
            "structured": [{"name": "measure", "artifact_type": "measure", "status": "approved"}],
            "computable": [],
            "events": [],
        }])

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, [topic, "measure"])
            assert result.exit_code == 0, result.output
            assert "Using deterministic CPG-on-FHIR builders" not in result.output
            assert (topic_dir / "computable" / "Measure-measure.json").exists()
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_guidance_note_when_no_cql(self, tmp_repo):
        """Guidance note emitted when no .cql file is present."""
        self._make_measure_topic(tmp_repo)

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            result = runner.invoke(formalize, ["test-measure", "test-measure"])
            assert result.exit_code == 0, result.output
            assert "rh-inf-cql" in result.output
            assert "author mode" in result.output

            # Library JSON written but no content[].data for CQL
            lib_files = list((tmp_repo / "topics" / "test-measure" / "computable").glob("Library-*.json"))
            assert len(lib_files) == 1
            library = json.loads(lib_files[0].read_text())
            cql_items = [c for c in library.get("content", []) if c.get("contentType") == "text/cql"]
            assert len(cql_items) == 0
        finally:
            os.environ.pop("LLM_PROVIDER", None)

    def test_cql_not_duplicated_on_rerun(self, tmp_repo):
        """Re-running formalize --force replaces, not appends, the CQL content item."""
        import base64

        computable_dir = self._make_measure_topic(tmp_repo)
        cql_source = b"library TestMeasureLogic version '1.0.0'\n"
        (computable_dir / "TestMeasureLogic.cql").write_bytes(cql_source)

        os.environ["LLM_PROVIDER"] = "stub"
        try:
            runner = CliRunner()
            runner.invoke(formalize, ["test-measure", "test-measure"])
            runner.invoke(formalize, ["test-measure", "test-measure", "--force"])

            lib_files = list(computable_dir.glob("Library-*.json"))
            library = json.loads(lib_files[0].read_text())
            cql_items = [c for c in library.get("content", []) if c.get("contentType") == "text/cql"]
            assert len(cql_items) == 1, "Must not duplicate text/cql content item on re-run"
        finally:
            os.environ.pop("LLM_PROVIDER", None)
