"""Regression tests for rh-skills formalize — CQL stub removal (T019).

Verifies that `rh-skills formalize` never auto-generates a .cql file. CQL
authoring is delegated to the `rh-inf-cql` skill (rh-skills cql …).
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from click.testing import CliRunner
from ruamel.yaml import YAML

from rh_skills.commands.formalize import formalize


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_tracking_yaml(topic_dir: Path, topic_name: str, artifact: str, artifact_type: str = "measure"):
    """Write a minimal tracking.yaml with a formalize-ready artifact."""
    y = YAML()
    tracking = {
        "topic": topic_name,
        "status": "active",
        "structured": [
            {
                "name": artifact,
                "type": artifact_type,
                "files": [f"topics/{topic_name}/structured/{artifact}.yaml"],
                "created_at": "2026-01-01T00:00:00Z",
            }
        ],
    }
    tracking_path = topic_dir / "tracking.yaml"
    with open(tracking_path, "w") as f:
        y.dump(tracking, f)
    return tracking_path


def _make_structured_artifact(structured_dir: Path, artifact: str, artifact_type: str = "measure"):
    """Write a minimal structured YAML artifact."""
    content = f"""\
artifact_type: {artifact_type}
name: {artifact}
display: Test Artifact
description: A test artifact for regression testing.
fhir_version: "4.0.1"
"""
    (structured_dir / f"{artifact}.yaml").write_text(content)


def _make_formalize_config(topic_dir: Path, topic_name: str):
    """Write a minimal formalize-config.yaml for a topic."""
    process_dir = topic_dir / "process"
    process_dir.mkdir(parents=True, exist_ok=True)
    content = f"""\
name: {_to_pascal(topic_name)}
id: {topic_name}
canonical: http://example.org/fhir
status: draft
version: 0.1.0
"""
    (process_dir / "formalize-config.yaml").write_text(content)


def _to_pascal(slug: str) -> str:
    return "".join(w.capitalize() for w in slug.split("-"))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def tmp_repo(tmp_path, monkeypatch):
    """Create a minimal repo layout and chdir into it."""
    (tmp_path / "topics").mkdir()
    (tmp_path / "sources").mkdir()
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("LLM_PROVIDER", "stub")
    return tmp_path


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestNoAutoGeneratedCql:
    """Ensure formalize never writes a .cql file automatically."""

    def test_formalize_does_not_write_cql_for_measure_artifact(self, tmp_repo):
        """A measure artifact with a Library strategy must NOT produce a .cql file."""
        topic = "lipid-management"
        artifact = "ldl-monitoring"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        _make_tracking_yaml(topic_dir, topic, artifact, "measure")
        _make_structured_artifact(structured_dir, artifact, "measure")
        _make_formalize_config(topic_dir, topic)

        runner = CliRunner()
        result = runner.invoke(formalize, [topic, artifact], catch_exceptions=False)

        # No .cql file should be written
        cql_files = list(computable_dir.glob("*.cql"))
        assert cql_files == [], (
            f"formalize must NOT write CQL files — found: {[f.name for f in cql_files]}. "
            "CQL authoring belongs to `rh-inf-cql` (author mode)."
        )

    def test_formalize_emits_rh_cql_guidance_for_library_artifacts(self, tmp_repo):
        """When a Library is in scope, formalize should emit a guidance note mentioning rh-inf-cql."""
        topic = "lipid-management"
        artifact = "ldl-monitoring"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        _make_tracking_yaml(topic_dir, topic, artifact, "measure")
        _make_structured_artifact(structured_dir, artifact, "measure")
        _make_formalize_config(topic_dir, topic)

        runner = CliRunner()
        result = runner.invoke(formalize, [topic, artifact], catch_exceptions=False)

        # Guidance note about rh-inf-cql should appear when Library is in scope
        combined = (result.output or "")
        if "Library" in combined or ".cql" in combined:
            assert "rh-inf-cql" in combined, (
                "When a Library resource is in scope, formalize must emit a guidance "
                "note referencing `rh-inf-cql` (author mode). Got output:\n" + combined
            )

    def test_formalize_cql_stub_not_in_source(self):
        """Regression: the auto-generated CQL stub block must not be present in formalize.py."""
        formalize_src = Path("src/rh_skills/commands/formalize.py")
        if not formalize_src.exists():
            pytest.skip("formalize.py not found at expected path")
        content = formalize_src.read_text()
        stub_marker = "library {cql_name} version"
        assert stub_marker not in content, (
            "The CQL auto-generation stub was found in formalize.py — "
            "this code must be removed. CQL authoring belongs to rh-inf-cql."
        )


class TestDecisionTableConditionStub:
    """Ensure decision-table PlanDefinition stubs include one action per condition row."""

    def _make_root_tracking_yaml(self, root: Path, topic_name: str, artifact: str, artifact_type: str):
        """Write a root tracking.yaml with the correct topics list format."""
        y = YAML()
        tracking = {
            "topics": [
                {
                    "name": topic_name,
                    "status": "active",
                    "events": [],
                    "structured": [
                        {
                            "name": artifact,
                            "artifact_type": artifact_type,
                            "files": [f"topics/{topic_name}/structured/{artifact}.yaml"],
                            "created_at": "2026-01-01T00:00:00Z",
                        }
                    ],
                }
            ]
        }
        with open(root / "tracking.yaml", "w") as f:
            y.dump(tracking, f)

    def _make_decision_table_artifact(self, structured_dir: Path, artifact: str, conditions: list):
        rows = "\n".join(
            f"    - id: {c['id']}\n      label: {c['label']}\n      values:\n        - 'yes'\n        - 'no'"
            for c in conditions
        )
        content = f"""\
artifact_type: decision-table
name: {artifact}
display: Test Decision Table
description: A test decision-table artifact.
fhir_version: "4.0.1"
sections:
  summary: Test summary
  conditions:
{rows}
  actions:
    - id: a1
      label: Refer to specialist
  rules:
    - id: r1
      when:
        {conditions[0]['id']}: 'yes'
      then:
        - a1
"""
        (structured_dir / f"{artifact}.yaml").write_text(content)

    def test_decision_table_actions_reference_condition_defines(self, tmp_repo):
        """Each condition row should produce one PlanDefinition action with a CQL expression."""
        topic = "bells-palsy"
        artifact = "management-decision"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        conditions = [
            {"id": "c1", "label": "Facial weakness present"},
            {"id": "c2", "label": "Eye closure affected"},
        ]
        self._make_root_tracking_yaml(tmp_repo, topic, artifact, "decision-table")
        self._make_decision_table_artifact(structured_dir, artifact, conditions)
        _make_formalize_config(topic_dir, topic)

        runner = CliRunner()
        result = runner.invoke(formalize, [topic, artifact], catch_exceptions=False)
        assert result.exit_code == 0, result.output

        plan_files = list(computable_dir.glob("PlanDefinition-*.json"))
        assert plan_files, "Expected a PlanDefinition JSON stub to be written"

        plan_json = json.loads(plan_files[0].read_text())
        actions = plan_json.get("action", [])
        assert len(actions) == 2, f"Expected 2 actions (one per condition), got {len(actions)}: {actions}"

        expressions = [
            a["condition"][0]["expression"]["expression"]
            for a in actions
            if a.get("condition")
        ]
        assert "FacialWeaknessPresent" in expressions, f"Missing CQL define for c1; got {expressions}"
        assert "EyeClosureAffected" in expressions, f"Missing CQL define for c2; got {expressions}"

    def test_decision_table_without_conditions_falls_back_to_generic_action(self, tmp_repo):
        """If L2 artifact has no conditions, fall back to generic stub action."""
        topic = "bells-palsy"
        artifact = "empty-decision"
        topic_dir = tmp_repo / "topics" / topic
        structured_dir = topic_dir / "structured"
        computable_dir = topic_dir / "computable"
        structured_dir.mkdir(parents=True)
        computable_dir.mkdir(parents=True)

        self._make_root_tracking_yaml(tmp_repo, topic, artifact, "decision-table")
        _make_structured_artifact(structured_dir, artifact, "decision-table")
        _make_formalize_config(topic_dir, topic)

        runner = CliRunner()
        result = runner.invoke(formalize, [topic, artifact], catch_exceptions=False)
        assert result.exit_code == 0, result.output

        plan_files = list(computable_dir.glob("PlanDefinition-*.json"))
        assert plan_files, "Expected a PlanDefinition JSON stub to be written"

        plan_json = json.loads(plan_files[0].read_text())
        actions = plan_json.get("action", [])
        assert len(actions) == 1
        assert actions[0]["title"] == "Initial action"
